import type { Product } from "@/components/ProductCard/ProductCard";

export const fallbackProducts: Product[] = [
  {
    id: 9001,
    name: "Pore Cleansing MD Face Wash",
    brand: "Minimalist",
    category: "cleanser",
    price: 299,
    currency: "INR",
    skin_types: "oily,combination,normal",
    concerns: "acne,oiliness,pores",
    key_ingredients: "Salicylic Acid 2%, Lactic Acid",
    description: "Deep cleansing face wash for acne-prone skin that helps remove excess oil and unclog pores.",
    avg_rating: 4.3,
    review_count: 15420,
    dermatologist_tested: true,
    clinically_proven: true,
    is_natural: false,
    is_fragrance_free: true,
    is_cruelty_free: true,
    is_vegan: true,
  },
  {
    id: 9002,
    name: "Niacinamide 10% Face Serum",
    brand: "Minimalist",
    category: "serum",
    price: 599,
    currency: "INR",
    skin_types: "oily,combination,normal",
    concerns: "oiliness,pores,acne,dark_spots",
    key_ingredients: "Niacinamide 10%, Zinc PCA",
    description: "Lightweight serum that helps support oil control, visible pores, and post-acne marks.",
    avg_rating: 4.4,
    review_count: 28400,
    dermatologist_tested: true,
    clinically_proven: true,
    is_natural: false,
    is_fragrance_free: true,
    is_cruelty_free: true,
    is_vegan: true,
  },
  {
    id: 9003,
    name: "Vitamin C 10% Serum",
    brand: "Plum",
    category: "serum",
    price: 790,
    currency: "INR",
    skin_types: "normal,dry,combination",
    concerns: "dullness,pigmentation,dark_spots",
    key_ingredients: "Vitamin C, Mandarin, Kakadu Plum",
    description: "Brightening serum for dullness and uneven tone with antioxidant support.",
    avg_rating: 4.2,
    review_count: 18300,
    dermatologist_tested: false,
    clinically_proven: false,
    is_natural: false,
    is_fragrance_free: false,
    is_cruelty_free: true,
    is_vegan: true,
  },
  {
    id: 9004,
    name: "Ceramide & Vitamin C Oil-Free Moisturizer",
    brand: "Dot & Key",
    category: "moisturizer",
    price: 495,
    currency: "INR",
    skin_types: "oily,combination,normal",
    concerns: "dryness,dullness,barrier",
    key_ingredients: "Ceramides, Vitamin C, Hyaluronic Acid",
    description: "Oil-free moisturizer that hydrates and supports the skin barrier without feeling heavy.",
    avg_rating: 4.1,
    review_count: 9200,
    dermatologist_tested: true,
    clinically_proven: false,
    is_natural: false,
    is_fragrance_free: false,
    is_cruelty_free: true,
    is_vegan: false,
  },
  {
    id: 9005,
    name: "Ultra Matte Dry Touch Sunscreen SPF 50",
    brand: "Re'equil",
    category: "sunscreen",
    price: 695,
    currency: "INR",
    skin_types: "oily,combination,normal",
    concerns: "tan,pigmentation,dark_spots",
    key_ingredients: "SPF 50, PA++++, UV Filters",
    description: "Matte sunscreen for daily protection with a dry-touch finish.",
    avg_rating: 4.4,
    review_count: 31200,
    dermatologist_tested: true,
    clinically_proven: true,
    is_natural: false,
    is_fragrance_free: false,
    is_cruelty_free: true,
    is_vegan: false,
  },
  {
    id: 9006,
    name: "Barrier Repair Moisturizer",
    brand: "The Derma Co",
    category: "moisturizer",
    price: 349,
    currency: "INR",
    skin_types: "dry,sensitive,normal",
    concerns: "dryness,redness,barrier",
    key_ingredients: "Ceramide Complex, Hyaluronic Acid",
    description: "Comforting moisturizer for dry or sensitive skin that needs barrier support.",
    avg_rating: 4.0,
    review_count: 7600,
    dermatologist_tested: true,
    clinically_proven: false,
    is_natural: false,
    is_fragrance_free: true,
    is_cruelty_free: true,
    is_vegan: false,
  },
  {
    id: 9007,
    name: "2% Salicylic Acid Serum",
    brand: "The Derma Co",
    category: "active",
    price: 499,
    currency: "INR",
    skin_types: "oily,combination",
    concerns: "acne,pores,oiliness",
    key_ingredients: "Salicylic Acid 2%, Witch Hazel",
    description: "Exfoliating acne-care serum for clogged pores and excess oil.",
    avg_rating: 4.2,
    review_count: 14100,
    dermatologist_tested: true,
    clinically_proven: true,
    is_natural: false,
    is_fragrance_free: false,
    is_cruelty_free: true,
    is_vegan: false,
  },
  {
    id: 9008,
    name: "Hyaluronic Acid Serum",
    brand: "L'Oreal Paris",
    category: "serum",
    price: 999,
    currency: "INR",
    skin_types: "dry,normal,combination,sensitive",
    concerns: "dryness,dullness,fine_lines",
    key_ingredients: "1.5% Hyaluronic Acid",
    description: "Hydrating serum for plumper-looking, smoother-feeling skin.",
    avg_rating: 4.3,
    review_count: 22500,
    dermatologist_tested: true,
    clinically_proven: true,
    is_natural: false,
    is_fragrance_free: false,
    is_cruelty_free: false,
    is_vegan: false,
  },
  {
    id: 9009,
    name: "Green Tea Oil-Free Moisturizer",
    brand: "Plum",
    category: "moisturizer",
    price: 470,
    currency: "INR",
    skin_types: "oily,combination",
    concerns: "oiliness,acne,dryness",
    key_ingredients: "Green Tea, Glycolic Acid",
    description: "Light moisturizer for oily and acne-prone skin.",
    avg_rating: 4.1,
    review_count: 16800,
    dermatologist_tested: false,
    clinically_proven: false,
    is_natural: false,
    is_fragrance_free: false,
    is_cruelty_free: true,
    is_vegan: true,
  },
  {
    id: 9010,
    name: "Rice Water Bright Cleansing Foam",
    brand: "The Face Shop",
    category: "cleanser",
    price: 650,
    currency: "INR",
    skin_types: "normal,dry,combination",
    concerns: "dullness,dryness",
    key_ingredients: "Rice Water, Moringa Oil",
    description: "Creamy cleanser for a soft, fresh cleanse.",
    avg_rating: 4.2,
    review_count: 13400,
    dermatologist_tested: false,
    clinically_proven: false,
    is_natural: false,
    is_fragrance_free: false,
    is_cruelty_free: false,
    is_vegan: false,
  },
  {
    id: 9011,
    name: "Hyaluronic Acid Watery Sun Gel SPF 50",
    brand: "Isntree",
    category: "sunscreen",
    price: 1650,
    currency: "INR",
    skin_types: "dry,normal,combination,sensitive",
    concerns: "tan,dryness,pigmentation",
    key_ingredients: "Hyaluronic Acid, SPF 50 PA++++",
    description: "Hydrating sunscreen with a lightweight gel texture.",
    avg_rating: 4.5,
    review_count: 8600,
    dermatologist_tested: false,
    clinically_proven: true,
    is_natural: false,
    is_fragrance_free: true,
    is_cruelty_free: true,
    is_vegan: true,
  },
  {
    id: 9012,
    name: "Retinol 0.3% Serum",
    brand: "Minimalist",
    category: "active",
    price: 699,
    currency: "INR",
    skin_types: "normal,dry,combination",
    concerns: "fine_lines,aging,dark_spots",
    key_ingredients: "Retinol 0.3%, Coenzyme Q10",
    description: "Beginner-friendly retinol serum for texture, fine lines, and uneven tone.",
    avg_rating: 4.2,
    review_count: 9700,
    dermatologist_tested: true,
    clinically_proven: true,
    is_natural: false,
    is_fragrance_free: true,
    is_cruelty_free: true,
    is_vegan: true,
  },
];
